spring:
  kafka:
    listener:
      ack-mode: manual_immediate
      concurrency: 3
      missing-topics-fatal: false
      default-error-handler:
        dead-letter-publish-failure-handler-bean-name: deadLetterLogger
        max-attempts: 3
        back-off:
          interval: 1000
          max-interval: 5000
          multiplier: 2.0
        retry-listener-bean-name: retryLogger

    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: '*'
        spring.json.value.default.type: com.ms.kafka.consumer.event.PaymentEvent
